import {
  Utensils,
  Coffee,
  Pizza,
  Beer,
  Wine,
  ChefHat,
  Car,
  Bus,
  TrainFront,
  Fuel,
  Bike,
  Plane,
  ParkingCircle,
  Home,
  Building2,
  Lightbulb,
  Wrench,
  Sofa,
  ShoppingBag,
  ShoppingCart,
  Shirt,
  Gift,
  Film,
  Music,
  Gamepad2,
  Ticket,
  Tv,
  HeartPulse,
  Pill,
  Stethoscope,
  Dumbbell,
  BookOpen,
  GraduationCap,
  Pencil,
  Wallet,
  TrendingUp,
  TrendingDown,
  HandCoins,
  PiggyBank,
  CreditCard,
  Landmark,
  Receipt,
  Percent,
  Baby,
  PawPrint,
  Dog,
  Cat,
  Smartphone,
  Wifi,
  Phone,
  Scissors,
  Sparkles,
  Luggage,
  MapPin,
  Shield,
  FileText,
  MoreHorizontal,
  Circle,
  Star,
  Bell,
  Umbrella,
  Droplet,
  Flame,
  Zap,
  Briefcase,
  Users,
  type LucideIcon,
} from "lucide-react";

const ICON_MAP: Record<string, LucideIcon> = {
  utensils: Utensils,
  coffee: Coffee,
  pizza: Pizza,
  beer: Beer,
  wine: Wine,
  "chef-hat": ChefHat,
  car: Car,
  bus: Bus,
  train: TrainFront,
  fuel: Fuel,
  bike: Bike,
  plane: Plane,
  parking: ParkingCircle,
  home: Home,
  building: Building2,
  lightbulb: Lightbulb,
  wrench: Wrench,
  sofa: Sofa,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  shirt: Shirt,
  gift: Gift,
  film: Film,
  music: Music,
  gamepad: Gamepad2,
  ticket: Ticket,
  tv: Tv,
  "heart-pulse": HeartPulse,
  pill: Pill,
  stethoscope: Stethoscope,
  dumbbell: Dumbbell,
  "book-open": BookOpen,
  "graduation-cap": GraduationCap,
  pencil: Pencil,
  wallet: Wallet,
  "trending-up": TrendingUp,
  "trending-down": TrendingDown,
  "hand-coins": HandCoins,
  "piggy-bank": PiggyBank,
  "credit-card": CreditCard,
  landmark: Landmark,
  receipt: Receipt,
  percent: Percent,
  baby: Baby,
  "paw-print": PawPrint,
  dog: Dog,
  cat: Cat,
  smartphone: Smartphone,
  wifi: Wifi,
  phone: Phone,
  scissors: Scissors,
  sparkles: Sparkles,
  luggage: Luggage,
  "map-pin": MapPin,
  shield: Shield,
  "file-text": FileText,
  "more-horizontal": MoreHorizontal,
  circle: Circle,
  star: Star,
  bell: Bell,
  umbrella: Umbrella,
  droplet: Droplet,
  flame: Flame,
  zap: Zap,
  briefcase: Briefcase,
  users: Users,
};

export function getCategoryIcon(icon: string): LucideIcon {
  return ICON_MAP[icon] ?? Circle;
}

export const CATEGORY_ICON_OPTIONS = Object.keys(ICON_MAP);

export default function CategoryIcon({
  icon,
  color,
  size = 18,
  className = "",
}: {
  icon: string;
  color: string;
  size?: number;
  className?: string;
}) {
  const Icon = ICON_MAP[icon] ?? Circle;
  return (
    <span
      className={`inline-flex shrink-0 items-center justify-center rounded-full ${className}`}
      style={{
        width: size * 1.9,
        height: size * 1.9,
        backgroundColor: color + "1f",
        color,
      }}
    >
      <Icon size={size} strokeWidth={2} />
    </span>
  );
}
